### ISSUE TITLE
Use @sensenet/hooks-react instead of own implementation

### ISSUE THREAD

**Issue by B3zo0** [sn-panda/snimageupload#7]
:watch:
estimate:
time spent:
_________

With the release of @sensenet/hooks-react package, you can use the useRepository hook from there. 

- [ ] Remove the use-repository.ts
- [x] Add @sensenet/hooks-react to package.json
- [x] Refactor code to use useRepository from there

**Comment by Khegyi** [comment]
You dont have to remove the repository-provider.ts
